name = "abm_cells"
uuid = "e02dbc4a-acad-4328-b312-46bcdeda689c"
authors = ["Allan Beveridge"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
